name: Fork and Add Collaborator

on:
  issues:
    types: [opened]  # Trigger when a new issue is created

jobs:
  process-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Test Fork with PAT
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/flatironsdevelopment/rails_node_test/forks
            # Fork the repository
      - name: Fork Repository
        id: fork
        uses: actions/github-script@v6
        with:
          github-token: process.env.PERSONAL_ACCESS_TOKEN
          script: |
            const baseRepo = context.repo.repo;
            const baseOwner = context.repo.owner;

            // Explicitly use the PERSONAL_ACCESS_TOKEN for authorization
            const forkResponse = await github.request('POST /repos/{owner}/{repo}/forks', {
              owner: baseOwner,
              repo: baseRepo,
              headers: {
                authorization: `token ${process.env.PERSONAL_ACCESS_TOKEN}`,
              },
            });

            console.log("Forked Repo Name:", forkResponse.data.full_name);
            return forkResponse.data.full_name;
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}