name: Fork and Transfer Repository

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    steps:
      # Fork the repository under your personal account
      - name: Fork Repository
        id: fork
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const baseRepo = context.repo.repo;
            const baseOwner = context.repo.owner;

            const forkResponse = await github.rest.repos.createFork({
              owner: baseOwner,
              repo: baseRepo,
            });

            console.log("Forked Repository:", forkResponse.data.full_name);
            return forkResponse.data.full_name; // Returns "mikefrederick/original-repo"

      # Transfer the forked repository to the organization
      - name: Transfer Repository to Organization
        id: transfer
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const forkRepoFullName = "${{ steps.fork.outputs.result }}"; // Pass output via YAML
            const [owner, repo] = forkRepoFullName.split('/');
            const newOwner = "flatironsdevelopment";

            const transferResponse = await github.rest.repos.transfer({
              owner: owner,
              repo: repo,
              new_owner: newOwner,
            });

            console.log("Transferred Repository:", transferResponse.data.full_name);
            return transferResponse.data.full_name;

      # Add a collaborator (Optional)
      - name: Add User to Transferred Repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const transferredRepoFullName = "${{ steps.transfer.outputs.result }}"; // Pass output via YAML
            const [owner, repo] = transferredRepoFullName.split('/');
            const username = context.payload.issue.body.trim(); // GitHub username from issue body

            await github.rest.repos.addCollaborator({
              owner: owner,
              repo: repo,
              username: username,
              permission: 'push', // Options: pull, triage, push, maintain, admin
            });

            console.log("User Added as Collaborator:", username);