name: Fork and Transfer Repository

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    steps:
      # Fork the repository under your personal account
      - name: Fork Repository
        id: fork
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const baseRepo = context.repo.repo;
            const baseOwner = context.repo.owner;

            const forkResponse = await github.rest.repos.createFork({
              owner: baseOwner,
              repo: baseRepo,
            });

            console.log("Forked Repository:", forkResponse.data.full_name);

            // Use GitHub Actions 'setOutput' to define the output
            core.setOutput('forkName', forkResponse.data.full_name);

      # Debug the fork output
      - name: Debug Fork Output
        run: |
          echo "Forked Repo: ${{ steps.fork.outputs.forkName }}"

      # Transfer the forked repository to the organization
      - name: Transfer Repository to Organization
        id: transfer
        uses: actions/github-script@v6
        env:
          FORK_REPO: ${{ steps.fork.outputs.forkName }}
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const forkRepoFullName = process.env.FORK_REPO?.trim(); // Ensure no null, empty, or undefined
            if (!forkRepoFullName) throw new Error("Fork repo full name is empty or undefined");

            const [owner, repo] = forkRepoFullName.split('/');
            const newOwner = "flatironsdevelopment";

            console.log(`Transferring repository: ${forkRepoFullName} to ${newOwner} under ${owner}`);

            const transferResponse = await github.rest.repos.transfer({
              owner: owner,
              repo: repo,
              new_owner: newOwner,
            });

            console.log("Transferred Repository:", transferResponse.data.full_name);