name: Fork and Add Collaborator

on:
  issues:
    types: [opened]  # Trigger when a new issue is created

jobs:
  process-issue:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Fork the base repository
      - name: Fork Repository
        id: fork
        uses: actions/github-script@v6
        with:
          script: |
            const baseRepo = context.repo.repo;
            const baseOwner = context.repo.owner;
            const forkResponse = await github.rest.repos.createFork({
              owner: baseOwner,
              repo: baseRepo,
            });
            return forkResponse.data.full_name;  # Returns "username/new-repo"

      # Add the user as a collaborator
      - name: Add User to Repo
        id: add-collaborator
        uses: actions/github-script@v6
        with:
          script: |
            const username = context.payload.issue.body.trim(); // Assuming GitHub username is in issue body
            const repoFullName = steps.fork.outputs.result;
            const [owner, repo] = repoFullName.split('/');
            
            await github.rest.repos.addCollaborator({
              owner: owner,
              repo: repo,
              username: username,
              permission: 'push', // Options: pull, triage, push, maintain, admin
            });
            return `https://github.com/${repoFullName}`;

      # Send an email with the repository link
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Your New Repository'
          body: |
            Hello,

            A new repository has been created for you. You have been added as a collaborator and can access it here:
            ${{ steps.add-collaborator.outputs.result }}

            Best,
            The Team
          to: recipient@example.com  # Replace with the user's email if known
          from: ${{ secrets.EMAIL_USERNAME }}